### ISSUE TITLE
Broken sinon.js include.

### ISSUE THREAD

**Issue by hanneskaeufler** [princed/karma-chai-plugins#24]
It seems sinon reorganized some files in the latest release which breaks karma-chai-plugins

The error I´m seeing is

```
WARN [watcher]: Pattern "/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-25/node_modules/karma-chai-plugins/node_modules/sinon/pkg/sinon.js" does not match any file.
```

And then a bunch of failures because sinon was not included properly :)

I´m not entirely sure but it could be related to this commit https://github.com/cjohansen/Sinon.JS/commit/c2704b19bc970d7bd6b773e8f13733f6e3f9ee33 and the path specified here: https://github.com/princed/karma-chai-plugins/blob/master/index.js#L89

**Comment by princed** [comment]
Would you like to make a PR?

**Comment by erikmunson** [comment]
@hanneskaeufler I'm having the same issue, and I came to the same conclusion as to the cause. Are you going to submit a PR? If not I will try to write one shortly.

**Comment by princed** [comment]
@erikmunson Please submit it, I'm going to do something right now :)

**Comment by erikmunson** [comment]
@princed So after looking into it further it turns out removing the `pkg` was a [totally unintentional bug](https://github.com/cjohansen/Sinon.JS/issues/761) introduced in `1.15.1`. The maintainer(s) are currently in the process of fixing and will supposedly be releasing a new version soon. In light of that fact, I'd say we shouldn't do anything in this package to fix.

**Comment by erikmunson** [comment]
@princed [I opened a PR](https://github.com/princed/karma-chai-plugins/pull/25) to use the most recently working version of Sinon until they fix their issues.

**Comment by princed** [comment]
Temporary solution is published.
